# FROM python:3.8-slim-buster
#
# WORKDIR /app
#
# COPY requirements.txt requirements.txt
# RUN pip3 install -r requirements.txt
#
#
# COPY ./app_convert_csv_to_json.py .
#
#
# ENTRYPOINT [ "python3", "./app_convert_csv_to_json.py"]
FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt


COPY ./app_convert_csv_to_json.py .


ENTRYPOINT [ "python3", "./app_convert_csv_to_json.py"]